# Generated by Django 5.0.2 on 2025-11-23 19:22

import django.db.models.deletion
import evmapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONFERENCE", "Conference"),
                            ("WORKSHOP", "Workshop"),
                            ("SEMINAR", "Seminar"),
                            ("CULTURAL", "Cultural Event"),
                            ("SPORTS", "Sports Event"),
                            ("CONCERT", "Concert"),
                            ("EXHIBITION", "Exhibition"),
                            ("NETWORKING", "Networking Event"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("organiser", models.CharField(max_length=100)),
                ("time", models.TimeField()),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=200)),
                (
                    "venue_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "venue_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("theme", models.CharField(max_length=200)),
                ("total_tickets", models.IntegerField()),
                (
                    "price_per_ticket",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "description",
                    models.CharField(
                        default="Fun Activities Followed by Dinner, Bring Your Friends and Family along!",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("free_ticket", models.BooleanField(default=False, null=True)),
                (
                    "group_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage for group bookings",
                        max_digits=5,
                    ),
                ),
                (
                    "payment_qr",
                    models.ImageField(
                        blank=True,
                        help_text="Upload QR Code for payment here",
                        null=True,
                        upload_to="event_qrs/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "volunteer_role",
                    models.CharField(
                        choices=[
                            ("Event Coordinator", "Event Coordinator"),
                            ("Registration Desk", "Registration Desk"),
                            ("Technical Support", "Technical Support"),
                            ("Guest Relations", "Guest Relations"),
                            ("Marketing", "Marketing & Promotion"),
                            ("Logistics", "Logistics & Setup"),
                            ("Security", "Security"),
                            ("First Aid", "First Aid & Safety"),
                            ("Photography", "Photography & Documentation"),
                            ("General", "General Volunteer"),
                        ],
                        default="General",
                        max_length=100,
                    ),
                ),
                ("skills", models.TextField(blank=True, null=True)),
                ("availability", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_tickets", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(default="", max_length=254, null=True)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid", models.BooleanField(default=False)),
                (
                    "payment_id",
                    models.CharField(blank=True, default="000", max_length=100),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        default=evmapp.models.generate_ticket_id,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("reminder_24h_sent", models.BooleanField(default=False)),
                ("reminder_2h_sent", models.BooleanField(default=False)),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False, help_text="User marked as paid."
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Admin verified payment."
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID entered by user.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "payment_screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="payment_screenshots/"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="evmapp.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(default="created", max_length=32)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=8)),
                ("method", models.CharField(blank=True, max_length=32, null=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="evmapp.booking",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="sponsors",
            field=models.ManyToManyField(to="evmapp.sponsor"),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
